//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    using UnityEngine.SceneManagement;
    
    
    public class ConectWhisSDK : TypedScene
    {
        
        public const string SceneName = "ConectWhisSDK";
        
        public static void Load(DataLoadScene argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            LoadScene(SceneName, loadSceneMode, argument);
        }
        
        public static UnityEngine.AsyncOperation LoadAsync(DataLoadScene argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            return LoadScene(SceneName, loadSceneMode, argument);
        }
    }
}
